language: python

python: 2.7

env:
  - TOX_ENV=

virtualenv:
  system_site_packages: true

install:
  - sudo apt-get install git python-git
  - pip install -U pip tox setuptools coveralls

script:
  - git --version
  - git --no-pager diff master
  - tox
  - coveralls --rcfile=.coveragerc
