language: python

python: 2.7

env:
  - TOX_ENV=

virtualenv:
  system_site_packages: true

install:
  - pip install -U pip tox setuptools coveralls

script:
  - git remote remove origin || true
  - git remote add origin https://github.com/FedericoRessi/pythoncourse.git
  - git fetch --all
  - tox
  - coveralls --rcfile=.coveragerc
